import { ReportType, ReportTypeMetadata } from '@/lib/types';

/**
 * Configuration for all 30+ report types from NYP store
 * https://store.newyorkpizza.nl/Reporting
 */
export const REPORT_TYPES_CONFIG: Record<ReportType, ReportTypeMetadata> = {
  OPERATIONAL: {
    type: 'OPERATIONAL',
    name: 'Operationeel rapport',
    description: 'Operational report with daily metrics',
    category: 'operational',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/Operationele',
  },
  TIME_KEEPING: {
    type: 'TIME_KEEPING',
    name: 'Urenregistratie rapport',
    description: 'Time keeping and clock-in/out report',
    category: 'operational',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/TimeKeeping',
  },
  MANUAL_DISCOUNT: {
    type: 'MANUAL_DISCOUNT',
    name: 'Handmatige kortingen',
    description: 'Manual discount report',
    category: 'financial',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/ManualDiscount',
  },
  CANCELLED_ORDERS: {
    type: 'CANCELLED_ORDERS',
    name: 'Geannuleerde bestellingen',
    description: 'Cancelled orders report',
    category: 'operational',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/CancelledOrders',
  },
  LABOUR: {
    type: 'LABOUR',
    name: 'Arbeidsrapport',
    description: 'Labour costs and hours worked',
    category: 'operational',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/Labour',
  },
  TIMEKEEPING_SUMMARY: {
    type: 'TIMEKEEPING_SUMMARY',
    name: 'Urenregistratie samenvatting',
    description: 'Timekeeping summary report',
    category: 'operational',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/TimekeepingSummary',
  },
  ZIPCODE_AREA_DELIVERY: {
    type: 'ZIPCODE_AREA_DELIVERY',
    name: 'Postcode gebied bezorging',
    description: 'Delivery by zipcode area',
    category: 'delivery',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/ZipcodeAreaDelivery',
  },
  ORDER_BY_HOURS: {
    type: 'ORDER_BY_HOURS',
    name: 'Bestellingen per uur',
    description: 'Orders by hour of day',
    category: 'operational',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/OrderByHours',
  },
  COUPON_DISCOUNT: {
    type: 'COUPON_DISCOUNT',
    name: 'Coupon kortingen',
    description: 'Coupon discount usage',
    category: 'financial',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/CouponDiscount',
  },
  USER_COMMENTS: {
    type: 'USER_COMMENTS',
    name: 'Klant opmerkingen',
    description: 'Customer comments and feedback',
    category: 'operational',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/UserComments',
  },
  LABOUR_EMPLOYEE: {
    type: 'LABOUR_EMPLOYEE',
    name: 'Arbeidsrapport per medewerker',
    description: 'Labour report per employee',
    category: 'operational',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/LabourEmployee',
  },
  LOCAL_CUSTOMER_DATA: {
    type: 'LOCAL_CUSTOMER_DATA',
    name: 'Lokale klantgegevens',
    description: 'Local customer data',
    category: 'operational',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/LocalCustomerData',
  },
  VARIANCE: {
    type: 'VARIANCE',
    name: 'Variantie rapport',
    description: 'Variance report',
    category: 'inventory',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/Variance',
  },
  STORE_ITEMS_SOLD: {
    type: 'STORE_ITEMS_SOLD',
    name: 'Verkochte artikelen',
    description: 'Store items sold report',
    category: 'operational',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/StoreItemsSold',
  },
  INVENTORY_IDEAL_USAGE: {
    type: 'INVENTORY_IDEAL_USAGE',
    name: 'Ideaal voorraadgebruik',
    description: 'Ideal inventory usage',
    category: 'inventory',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/InventoryIdealUsage',
  },
  TIP: {
    type: 'TIP',
    name: 'Fooien rapport',
    description: 'Tips report',
    category: 'financial',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/Tip',
  },
  ISSUED_CLIENT_CREDIT: {
    type: 'ISSUED_CLIENT_CREDIT',
    name: 'Uitgegeven klanttegoed',
    description: 'Issued client credit',
    category: 'financial',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/IssuedClientCredit',
  },
  ISSUED_CLIENT_BALANCE: {
    type: 'ISSUED_CLIENT_BALANCE',
    name: 'Klantsaldo rapport',
    description: 'Client balance report',
    category: 'financial',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/IssuedClientBalance',
  },
  EXPENSES: {
    type: 'EXPENSES',
    name: 'Uitgaven rapport',
    description: 'Expenses report',
    category: 'financial',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/Expenses',
  },
  INVENTORY_DELIVERY: {
    type: 'INVENTORY_DELIVERY',
    name: 'Voorraad levering',
    description: 'Inventory delivery report',
    category: 'inventory',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/InventoryDelivery',
  },
  INVENTORY_LOSS: {
    type: 'INVENTORY_LOSS',
    name: 'Voorraad verlies',
    description: 'Inventory loss report',
    category: 'inventory',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/InventoryLoss',
  },
  INVENTORY_RETURNS: {
    type: 'INVENTORY_RETURNS',
    name: 'Voorraad retouren',
    description: 'Inventory returns report',
    category: 'inventory',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/InventoryReturns',
  },
  CASH_DRAWER_AUDIT: {
    type: 'CASH_DRAWER_AUDIT',
    name: 'Kaslade controle',
    description: 'Cash drawer audit report',
    category: 'financial',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/CashDrawerAudit',
  },
  INVENTORY_DAILY_COUNT: {
    type: 'INVENTORY_DAILY_COUNT',
    name: 'Dagelijkse voorraadtelling',
    description: 'Daily inventory count',
    category: 'inventory',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/InventoryDailyCount',
  },
  SERVICE: {
    type: 'SERVICE',
    name: 'Service rapport',
    description: 'Service and delivery metrics',
    category: 'delivery',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/Service',
  },
  DAILY_SALES: {
    type: 'DAILY_SALES',
    name: 'Dagelijkse verkoop',
    description: 'Daily sales report',
    category: 'financial',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/DailySales',
  },
  COUPON_ANALYSIS: {
    type: 'COUPON_ANALYSIS',
    name: 'Coupon analyse',
    description: 'Coupon usage analysis',
    category: 'financial',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/CouponAnalysis',
  },
  VARIANCE_PER_STOCK_PRODUCT: {
    type: 'VARIANCE_PER_STOCK_PRODUCT',
    name: 'Variantie per voorraadproduct',
    description: 'Variance per stock product',
    category: 'inventory',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/VariancePerStockProduct',
  },
  DRIVER_REPORT: {
    type: 'DRIVER_REPORT',
    name: 'Bezorger rapport',
    description: 'Driver performance report',
    category: 'delivery',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/DriverReport',
  },
  PAYMENT_METHOD: {
    type: 'PAYMENT_METHOD',
    name: 'Betaalmethode rapport',
    description: 'Payment method breakdown',
    category: 'financial',
    fileType: 'excel',
    nypUrl: '/Reporting/Generate/PaymentMethod',
  },
};

export function getReportTypeConfig(type: ReportType): ReportTypeMetadata {
  return REPORT_TYPES_CONFIG[type];
}

export function getAllReportTypes(): ReportTypeMetadata[] {
  return Object.values(REPORT_TYPES_CONFIG);
}
